name: 'Scan github action'
description: 'A github action to scan repositories Dockerfile'
inputs:
  GH_TOKEN:
    description: 'A Github PAT'
    required: true
    
outputs:
  ENABLED:
    description: 'Enabled security check'
    value: ${{ steps.configuring_pipeline.outputs.ENABLED }}
  THRESHOLD:
    description: 'Threhold to break pipeline'
    value: ${{ steps.configuring_pipeline.outputs.THRESHOLD }}
  ORGANIZATION:
    description: 'Threhold to break pipeline'
    value: ${{ steps.configuring_pipeline.outputs.THRESHOLD }}

runs:
  using: docker # we are saying this action will run on docker
  name: configuring_pipeline
  image: 'Dockerfile' # we will use our own Dockerfile to build an image and run it.
  env:
    GH_TOKEN: ${{ inputs.GH_TOKEN }}

# for publishing purposes
branding: #generates a logo for our action
  icon: arrow-down #icon of the image
  color: blue # background color of the logo of our action
